name: WLED compile

on:
    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Set up Node.js
      uses: actions/setup-node@v4
    - name: Run PlatformIO
      run: |
        rm -rf /tmp/WLEDtemp/* || true
        mkdir -p /tmp/WLEDtemp
        wget https://github.com/moonmodules/WLED/archive/refs/heads/mdev.zip -O /tmp/WLEDtemp/mm.zip
        unzip /tmp/WLEDtemp/mm.zip -d /tmp/WLEDtemp
        find /tmp/WLEDtemp -maxdepth 1 -mindepth 1 -name "*" -type d >> /tmp/WLEDtemp/wledfoldername
        cd `cat /tmp/WLEDtemp/wledfoldername`
        npm install
        echo '[env:custom_build]' >>platformio.ini
        echo 'extends = env:esp32c3mini_dio_4MB_M' >>platformio.ini
        echo 'build_flags = ${env:esp32c3mini_dio_4MB_M.build_flags} -D SR_DEBUG -D LOLIN_WIFI_FIX -D WLED_ENABLE_DMX -D WLED_ENABLE_MQTT -D WLED_DISABLE_LOXONE -D WLED_ENABLE_WEBSOCKETS -D WLED_ENABLE_ADALIGHT -D WLED_ENABLE_PIXART -D WLED_DISABLE_ALEXA -D WLED_DISABLE_HUESYNC -D DEFAULT_LED_COUNT=0 -D ABL_MILLIAMPS_DEFAULT=2000 -D CLIENT_SSID='\''"IoT24"'\'' -D CLIENT_PASS='\''"OICu81too"'\'' -D USERMOD_AUTO_SAVE -D USERMOD_ROTARY_ENCODER_UI -D USERMOD_MODE_SORT -D USERMOD_ANIMATED_STAIRCASE -D USERMOD_SENSORSTOMQTT' >>platformio.ini
        echo 'lib_deps = ' >>platformio.ini
        echo '  ${env:esp32c3mini_dio_4MB_M.lib_deps}' >>platformio.ini
        echo '  olikraus/U8g2 @ ^2.28.8' >>platformio.ini
        echo '  Wire' >>platformio.ini
        echo '  adafruit/Adafruit BMP280 Library @ 2.1.0' >>platformio.ini
        echo '  adafruit/Adafruit CCS811 Library @ 1.0.4' >>platformio.ini
        echo '  adafruit/Adafruit Si7021 Library @ 1.4.0' >>platformio.ini
        echo '  adafruit/Adafruit Unified Sensor' >>platformio.ini
        
        pio run -e custom_build || pio run -e custom_build
    - name: Copy Files
      run: |
        cd $GITHUB_WORKSPACE
        git rm -r $GITHUB_WORKSPACE/*.bin || true
        WLEDFOLDERNAME=`cat /tmp/WLEDtemp/wledfoldername`
        cp ${WLEDFOLDERNAME}/build_output/firmware/custom_build.bin $GITHUB_WORKSPACE/
        date -I | tr -d '\n' >$GITHUB_WORKSPACE/last_update_date.txt
    - name: Commit Files
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add $GITHUB_WORKSPACE/custom_build.bin
        git add $GITHUB_WORKSPACE/last_update_date.txt
        git commit -m "Commit Custom Build"
        git push origin main
